version: '3.8'

x-localtime: &host_localtime
  type: bind
  source: /etc/localtime
  target: /etc/localtime
  read_only: true

x-logging: &logging
  logging:
    driver: json-file
    options:
      tag: "{{.Name}}"
      max-size: ${LOG_MAX_SIZE:-5m}
      max-file: ${LOG_MAX_FILE:-1}

services:
  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    command: bash -c "python main.py"
    restart: unless-stopped
    env_file:
      - .env
    <<: *logging
    networks:
      internal: { }
      external: { }


networks:
  internal:
    name: server_internal
    driver: bridge
    internal: true
  external:
    name: server_external
    driver: bridge